name = "redirect-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
SUPABASE_URL = "https://vtlwptockofzbllnsyrg.supabase.co"
SUPABASE_ANON_KEY = "sb_publishable_0MWvjujUhXVBNq7P-30baA_Jqr1SYsm"
